name: admob_flutter
description: Admob plugin that shows banner ads using native platform views.
version: 2.0.0
homepage: https://github.com/kmcgill88/admob_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: 1.11.0

flutter:
  plugin:
    platforms:
      android:
        package: com.shatsy.admobflutter
        pluginClass: AdmobFlutterPlugin
      ios:
        pluginClass: AdmobFlutterPlugin
