name: admob_flutter
description: Admob plugin that shows banner ads using native platform views.
version: 1.0.0-beta
homepage: https://github.com/kmcgill88/admob_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6

dev_dependencies:
  pedantic: ^1.8.0

flutter:
  plugin:
    platforms:
      android:
        package: com.shatsy.admobflutter
        pluginClass: AdmobFlutterPlugin
      ios:
        pluginClass: AdmobFlutterPlugin
